# Generated by Django 4.0.6 on 2022-08-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_add_data', 'can add a new data'),)},
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='forgot_logged',
            field=models.BooleanField(default=False, help_text='Only true if validate otp forgot get successful'),
        ),
    ]
