# Generated by Django 4.0.6 on 2022-08-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_alter_phoneotp_forgot_logged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='forgot',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='forgot_logged',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='logged',
        ),
        migrations.RemoveField(
            model_name='user',
            name='standard',
        ),
    ]
