# Generated by Django 4.0.6 on 2022-08-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_phoneotp_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_login',
        ),
    ]
