# Generated by Django 4.0.6 on 2022-08-08 11:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_listorder_user'),
        ('user', '0004_phoneotp_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPictureAddress',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.IntegerField(blank=True, unique=True)),
                ('user_profile', models.ImageField(blank=True, null=True, upload_to=user.models.upload_to_profile)),
                ('user_signature', models.ImageField(blank=True, null=True, upload_to=user.models.upload_to_signature)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(max_length=10, validators=[user.models.only_digit, django.core.validators.MinLengthValidator(10)])),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_signature',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_login',
        ),
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.listorder'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='profile',
            name='pic_add',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userpictureaddress'),
        ),
    ]
