# Generated by Django 4.0.6 on 2022-08-06 19:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_listorder_user'),
        ('user', '0005_remove_user_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.listorder'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001AEE11B0670>', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,14}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address'),
        ),
    ]
