# Generated by Django 4.0.6 on 2022-08-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userpictureaddress_remove_profile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpictureaddress',
            name='user',
        ),
    ]
