# Generated by Django 4.0.6 on 2022-08-07 20:01

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_profile_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to_profile),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_signature',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to_signature),
        ),
    ]
