# Generated by Django 4.0.6 on 2022-08-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_userpicture_remove_profile_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
