# Generated by Django 4.0.6 on 2022-08-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_picture_remove_orderitem_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='id_product',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
