# Generated by Django 4.0.6 on 2022-08-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_listorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listorder',
            name='user',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
