# Generated by Django 4.0.6 on 2022-08-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_listorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listorder',
            name='date_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listorder',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listorder',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
