# Generated by Django 4.0.6 on 2022-08-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_listorder_date_submitted_listorder_is_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listorder',
            name='choices',
            field=models.CharField(choices=[('old', 'received'), ('new', 'completing'), ('future', 'after_new')], default='new', max_length=100),
        ),
        migrations.AlterField(
            model_name='listorder',
            name='date_submitted',
            field=models.DateField(auto_now=True),
        ),
    ]
